const catalogoInsumos = [
  { "codigo": "100", "nombre": "Abre Boca" },
  { "codigo": "261", "nombre": "Adaptador" },
  { "codigo": "262", "nombre": "Alargador de Herramientas" },
  { "codigo": "101", "nombre": "Algodonero" },
  { "codigo": "102", "nombre": "Alicate" },
  { "codigo": "103", "nombre": "Ambu Adulto" },
  { "codigo": "104", "nombre": "Ambu Pediatrico" },
  { "codigo": "106", "nombre": "Arco Radiolúcido" },
  { "codigo": "105", "nombre": "Arco de Young" },
  { "codigo": "263", "nombre": "Arranque Del Taladro" },
  { "codigo": "259", "nombre": "BANDEJA DE EXAMEN C/SONDA PERIODONTAL" },
  { "codigo": "260", "nombre": "BANDEJA DE EXAMEN S/SONDA PERIODONTAL" },
  { "codigo": "107", "nombre": "Bandeja Sola" },
  { "codigo": "108", "nombre": "Basurero" },
  { "codigo": "109", "nombre": "Bayoneta" },
  { "codigo": "110", "nombre": "Bisturí" },
  { "codigo": "264", "nombre": "Broca Inicial" },
  { "codigo": "111", "nombre": "Bruñidor" },
  { "codigo": "242", "nombre": "CAJA DE CIRUGÍA" },
  { "codigo": "243", "nombre": "CAJA DE ENDODONCIA CON LIMAS" },
  { "codigo": "244", "nombre": "CAJA DE IMPLANTES 3I" },
  { "codigo": "246", "nombre": "CAJA DE IMPLANTES MIS" },
  { "codigo": "247", "nombre": "CAJA DE IMPLANTES NOBEL BRANEMARK SYSTEM" },
  { "codigo": "249", "nombre": "CAJA DE IMPLANTES NOBEL PROSTETIC" },
  { "codigo": "248", "nombre": "CAJA DE IMPLANTES NOBEL REPLACE" },
  { "codigo": "250", "nombre": "CAJA DE IMPLANTES ZIMMER" },
  { "codigo": "251", "nombre": "CAJA DE PERIODONCIA BÁSICA" },
  { "codigo": "252", "nombre": "CAJA DE PERIODONCIA COLGAJO" },
  { "codigo": "253", "nombre": "CAJA DE REMODELACIÓN OSEA" },
  { "codigo": "245", "nombre": "CAJA IMPLANTES 3I.1" },
  { "codigo": "113", "nombre": "Caja Metalica" },
  { "codigo": "112", "nombre": "Caja de Endodoncia Sola" },
  { "codigo": "114", "nombre": "Calibrador" },
  { "codigo": "116", "nombre": "Canulas Mayo" },
  { "codigo": "117", "nombre": "Carpule" },
  { "codigo": "118", "nombre": "Cincel" },
  { "codigo": "119", "nombre": "Clamps" },
  { "codigo": "120", "nombre": "Compresas" },
  { "codigo": "121", "nombre": "Condensador" },
  { "codigo": "265", "nombre": "Conductores" },
  { "codigo": "122", "nombre": "Conexiones De Aspiracion" },
  { "codigo": "123", "nombre": "Conos De Papel" },
  { "codigo": "124", "nombre": "Contra Angulo" },
  { "codigo": "125", "nombre": "Copela" },
  { "codigo": "126", "nombre": "Cubetas" },
  { "codigo": "127", "nombre": "Cuchareta De Alveolo Curva" },
  { "codigo": "129", "nombre": "Cuchareta De Caries" },
  { "codigo": "128", "nombre": "Cuchareta de Alveolo Recta" },
  { "codigo": "130", "nombre": "Cureta" },
  { "codigo": "115", "nombre": "Cánulas de Aspiración Metálica" },
  { "codigo": "131", "nombre": "Delantal" },
  { "codigo": "266", "nombre": "Destornillador Manual" },
  { "codigo": "133", "nombre": "Dicalero" },
  { "codigo": "132", "nombre": "Electrobisturi" },
  { "codigo": "134", "nombre": "Elevador Apical" },
  { "codigo": "135", "nombre": "Elevador Recto" },
  { "codigo": "136", "nombre": "Elevador Winter" },
  { "codigo": "137", "nombre": "Empaquetador de Hilo Retractor" },
  { "codigo": "138", "nombre": "Endo Block" },
  { "codigo": "139", "nombre": "Endo Point" },
  { "codigo": "140", "nombre": "Escobilla De Profilaxis" },
  { "codigo": "141", "nombre": "Espaciador" },
  { "codigo": "142", "nombre": "Espatula De Cemento" },
  { "codigo": "144", "nombre": "Espatula De Composite" },
  { "codigo": "145", "nombre": "Espatula De Godiva" },
  { "codigo": "146", "nombre": "Espatula De Lecrón" },
  { "codigo": "148", "nombre": "Espejo Bucal" },
  { "codigo": "143", "nombre": "Espátula De Cera" },
  { "codigo": "147", "nombre": "Espátula Ionómero" },
  { "codigo": "254", "nombre": "FRESARIO CON FRESAS" },
  { "codigo": "6024057", "nombre": "FRESAS" },
  { "codigo": "277", "nombre": "Filtros Para Canulas De Recoleccion De Huesos" },
  { "codigo": "149", "nombre": "Forceps Bayoneta" },
  { "codigo": "150", "nombre": "Forceps Curvo Sobre Borde" },
  { "codigo": "151", "nombre": "Forceps Recto" },
  { "codigo": "153", "nombre": "Frasco Plastico" },
  { "codigo": "152", "nombre": "Frasco de Vidrio" },
  { "codigo": "154", "nombre": "Fresa" },
  { "codigo": "155", "nombre": "Fresa Gate" },
  { "codigo": "267", "nombre": "Fresa Piloto" },
  { "codigo": "156", "nombre": "Fresa Pimpollo" },
  { "codigo": "157", "nombre": "Fresa Piso" },
  { "codigo": "158", "nombre": "Fresario Solo" },
  { "codigo": "159", "nombre": "Gancho De localizador De Apice" },
  { "codigo": "160", "nombre": "Ganchos Gillis o Gille" },
  { "codigo": "161", "nombre": "Gubia" },
  { "codigo": "162", "nombre": "Gutaperchero" },
  { "codigo": "268", "nombre": "ICD100" },
  { "codigo": "269", "nombre": "Indicador De Profundidad" },
  { "codigo": "270", "nombre": "Indicadores De Direccion" },
  { "codigo": "163", "nombre": "Insertos de Cavitrón" },
  { "codigo": "255", "nombre": "JUEGO DE EXAMEN" },
  { "codigo": "164", "nombre": "Jacquette" },
  { "codigo": "271", "nombre": "Jeringa De Irrigacion" },
  { "codigo": "166", "nombre": "Legra" },
  { "codigo": "167", "nombre": "Lentulo" },
  { "codigo": "168", "nombre": "Lima Acodada" },
  { "codigo": "169", "nombre": "Lima Individual" },
  { "codigo": "170", "nombre": "Lima Para Hueso" },
  { "codigo": "171", "nombre": "Lima Periodontal" },
  { "codigo": "172", "nombre": "Limpia Fresas" },
  { "codigo": "272", "nombre": "Llave De Tuerca" },
  { "codigo": "165", "nombre": "Llaves" },
  { "codigo": "273", "nombre": "Llaves Atornilladoras" },
  { "codigo": "173", "nombre": "Loseta" },
  { "codigo": "174", "nombre": "Mangas" },
  { "codigo": "175", "nombre": "Mango De Bisturí Con Regla Métrica" },
  { "codigo": "176", "nombre": "Mango De Bisturí Recto" },
  { "codigo": "177", "nombre": "Mango De Bisturí Universal" },
  { "codigo": "178", "nombre": "Mango De Espejo Hexagonal" },
  { "codigo": "179", "nombre": "Marcarilla Adulto" },
  { "codigo": "180", "nombre": "Marcarilla Pediatricas" },
  { "codigo": "181", "nombre": "Micro Motor" },
  { "codigo": "182", "nombre": "Microtorulas" },
  { "codigo": "183", "nombre": "Naricera" },
  { "codigo": "185", "nombre": "Paquete Gasa" },
  { "codigo": "186", "nombre": "Paquete Ropa Estéril Desechable" },
  { "codigo": "184", "nombre": "Paños De Campos" },
  { "codigo": "187", "nombre": "Perforador de Goma" },
  { "codigo": "188", "nombre": "Piedra de Arkansas Lisa Dura" },
  { "codigo": "189", "nombre": "Pieza de Mano" },
  { "codigo": "190", "nombre": "Pincelador" },
  { "codigo": "191", "nombre": "Pinza Adson Anatomica" },
  { "codigo": "192", "nombre": "Pinza Adson Curva" },
  { "codigo": "193", "nombre": "Pinza Adsson Anatomica Quirurgica" },
  { "codigo": "194", "nombre": "Pinza Anatómica" },
  { "codigo": "195", "nombre": "Pinza Backey Recta" },
  { "codigo": "196", "nombre": "Pinza Backhaus De Cirugía" },
  { "codigo": "197", "nombre": "Pinza De Exámen (Hemostatica)" },
  { "codigo": "198", "nombre": "Pinza Kelly Curva" },
  { "codigo": "199", "nombre": "Pinza Kelly Recta" },
  { "codigo": "200", "nombre": "Pinza Mosquito" },
  { "codigo": "201", "nombre": "Pinza Müller" },
  { "codigo": "202", "nombre": "Porta Aguja Castroviejo" },
  { "codigo": "203", "nombre": "Porta Aguja Fino" },
  { "codigo": "204", "nombre": "Porta Aguja Tradicional" },
  { "codigo": "205", "nombre": "Porta Agujas Mathieu" },
  { "codigo": "206", "nombre": "Porta Clamps" },
  { "codigo": "207", "nombre": "Porta Disco" },
  { "codigo": "208", "nombre": "Porta Matriz" },
  { "codigo": "209", "nombre": "Puntas De Goma" },
  { "codigo": "210", "nombre": "Puntas De Guantes" },
  { "codigo": "211", "nombre": "Puntas De Jeringa Triple" },
  { "codigo": "212", "nombre": "Raspador Freer" },
  { "codigo": "213", "nombre": "Raspador Morse" },
  { "codigo": "214", "nombre": "Receptal" },
  { "codigo": "274", "nombre": "Regla" },
  { "codigo": "215", "nombre": "Regla De Endodoncia" },
  { "codigo": "275", "nombre": "Repuesto" },
  { "codigo": "216", "nombre": "Retractor Columbia" },
  { "codigo": "217", "nombre": "Retractor Minnesota" },
  { "codigo": "218", "nombre": "Riñon" },
  { "codigo": "256", "nombre": "SACHET DE ENDODONCIA" },
  { "codigo": "6024058", "nombre": "SEPARADORES" },
  { "codigo": "257", "nombre": "SET DE PERIODONCIA" },
  { "codigo": "258", "nombre": "SET PORTA DAPPENS" },
  { "codigo": "220", "nombre": "Separador Farafeub" },
  { "codigo": "221", "nombre": "Separador Langelbelck" },
  { "codigo": "222", "nombre": "Separador Volkmann" },
  { "codigo": "219", "nombre": "Separador de Labios" },
  { "codigo": "223", "nombre": "Sonda Carie Curva" },
  { "codigo": "224", "nombre": "Sonda Exámen Periodontal" },
  { "codigo": "225", "nombre": "Sonda Folley" },
  { "codigo": "226", "nombre": "Sonda Navers Periodontal" },
  { "codigo": "227", "nombre": "Sonda Nelaton" },
  { "codigo": "228", "nombre": "Sonda Recta" },
  { "codigo": "276", "nombre": "Taladro De Extension" },
  { "codigo": "229", "nombre": "Tallador" },
  { "codigo": "230", "nombre": "Tela adhesiva" },
  { "codigo": "231", "nombre": "Tijera" },
  { "codigo": "232", "nombre": "Tijera Corta Alambre" },
  { "codigo": "233", "nombre": "Tijera De Encia Curva" },
  { "codigo": "234", "nombre": "Tijera De Encia Recta" },
  { "codigo": "235", "nombre": "Tijera Iris Recta" },
  { "codigo": "236", "nombre": "Tijera La Grange Doble Curva" },
  { "codigo": "237", "nombre": "Tonillos" },
  { "codigo": "238", "nombre": "Torulas" },
  { "codigo": "239", "nombre": "Tubo Endotraqueal" },
  { "codigo": "240", "nombre": "Turbina" },
  { "codigo": "241", "nombre": "Vaso Dappen" }
];
